services:
  app:
    image: ghcr.io/ungaul/applications-helper:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: applications-helper
    stdin_open: true
    tty: true
    environment:
      - OLLAMA_API_KEY=
      - OPENAI_API_KEY=
      - AI_ENDPOINT=https://api.openai.com/v1
      - GPT_MODEL=gpt-4.1-mini
      - TEMPLATE_CV=/app/template_cv.docx
      - TEMPLATE_COVER_LETTER=/app/template_cover_letter.docx
      - OUTPUT_BASE_DIR=/app/output
      - TRACKER_FILE=/app/list.csv
      - ADZUNA_APP_ID=
      - ADZUNA_APP_KEY=
      - JOB_SEARCHES=5
      - CV_HEADER_TEMPLATE=
    volumes:
      - ./Template/CV.docx:/app/template_cv.docx:ro
      - ./Template/Cover_Letter.docx:/app/template_cover_letter.docx:ro
      - .:/app/output
      - ./list.csv:/app/list.csv